<a href="https://colab.research.google.com/github/PRITHASAMANTA/Data-Science-Material/blob/main/Math_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Determinants and Inverse of a Mtrix

determinants are the scalar value that provides information about matrix properties
-calculated only for square matrix
det(A)=0, a is singular

In [3]:
import numpy as np

In [4]:
A=np.array([[2,3],[1,4]])

In [5]:
determinant= np.linalg.det(A)
determinant

np.float64(5.000000000000001)

#Determinants and Inverse of a matrix
-Inverse of a matrix
-denoted as A-1
-product of a matrix and its inverse is the identity matrix
A,A-1=I
-matrix is invertible only if det(A) not eq 0
A-1=1/det(A)[d -b
             -c  a]

In [8]:
inverse=np.linalg.inv(A)
print("inverse of A is :\n" , inverse)

inverse of A is :
 [[ 0.8 -0.6]
 [-0.2  0.4]]


#EigenValues and Eigen Vectors:
A.v=lamda.v.then vis the eigenvector
and lamda is the eigen value


In [10]:
eigenvalues,eigenvectors= np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[1. 5.]
[[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


In [11]:
B= np.array([[4,2],[1,1]])
eigval,eigvec = np.linalg.eig(B)
print(eigval)
print(eigvec)

[4.56155281 0.43844719]
[[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]


Matrix Decomposition : process of breaking the matrix to analyze the problem
#1. Singular Value decomposition(SVD)
 it decomposes a matrix into 3 parts
 A=U.sigma.V^t
 u=left singular/orthogonal matrix
 sigma:diagonal matrix
 v^t=right singular vector

In [13]:
U,S,Vt= np.linalg.svd(A)
print("U is :\n", U)
print("S is :\n", S)
print("Vt is :\n", Vt)

U is :
 [[-0.65520174 -0.75545395]
 [-0.75545395  0.65520174]]
S is :
 [5.39834564 0.92620968]
Vt is :
 [[-0.38268343 -0.92387953]
 [-0.92387953  0.38268343]]


Ex 1 : Calculate the determinant and inverse of a matrix

In [27]:
A= np.array([[2,3,4], [4,5,6], [7,8,9]])
det2=np.linalg.det(A)
print("Determinant of A is :\n", det2)

Determinant of A is :
 0.0


as determinant is 0 means it is singular matrix and it is not inversable

In [28]:

Inverse=np.linalg.inv(A)
print("Inverse of A is :\n", Inverse)

LinAlgError: Singular matrix

# As the det is 0 so it is not inversable, thats why error coming


In [30]:
A = np.array([[2, 1, 3],
              [1, 0, 2],
              [3, 2, 1]])

det = np.linalg.det(A)
print("Determinant:", det)

Determinant: 3.000000000000001


In [31]:
inv = np.linalg.inv(A)
print("Inverse:\n", inv)

Inverse:
 [[-1.33333333  1.66666667  0.66666667]
 [ 1.66666667 -2.33333333 -0.33333333]
 [ 0.66666667 -0.33333333 -0.33333333]]


# Ex 2 compute eigen value and eigen vector

In [32]:
eigenval2,eigenvec2= np.linalg.eig(A)
print("Eigen values are :\n", eigenval2)
print("Eigen vectors are :\n", eigenvec2)

Eigen values are :
 [ 5.34849393 -0.26984088 -2.07865306]
Eigen vectors are :
 [[-0.67934373 -0.59990492 -0.42261825]
 [-0.3650547   0.77587586 -0.5145403 ]
 [-0.63657455  0.19527095  0.74608451]]


#SVD

In [33]:
U2,S2,vt=np.linalg.svd(A)
print("U is :\n", U2)
print("S is :\n", S2)
print("Vt is :\n", vt)

U is :
 [[-0.67934373 -0.42261825 -0.59990492]
 [-0.3650547  -0.5145403   0.77587586]
 [-0.63657455  0.74608451  0.19527095]]
S is :
 [5.34849393 2.07865306 0.26984088]
Vt is :
 [[-0.67934373 -0.3650547  -0.63657455]
 [ 0.42261825  0.5145403  -0.74608451]
 [ 0.59990492 -0.77587586 -0.19527095]]
